// app/skills/page.tsx
import Link from 'next/link';
import { ArrowRightCircle } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { getSkills, sanityImageUrl } from '@/lib/sanity';
import type { Skill } from '@/lib/types';

function compareExperience(a: Skill, b: Skill): number {
  const aExp = Number.parseInt(a.experience ?? '0', 10);
  const bExp = Number.parseInt(b.experience ?? '0', 10);
  if (aExp > bExp) return -1;
  if (aExp < bExp) return 1;
  return 0;
}

function groupSkills(skills: Skill[]): Record<string, Skill[]> {
  const grouped: Record<string, Skill[]> = {};
  const sorted = [...skills].sort(compareExperience);

  for (const skill of sorted) {
    const key = skill.category ?? 'Other';
    grouped[key] = grouped[key] ? [...grouped[key], skill] : [skill];
  }

  return grouped;
}

export default async function SkillsPage() {
  const skills = await getSkills();
  const grouped = groupSkills(skills);
  const categories = Object.keys(grouped);

  return (
    <>
      <h1 className="page_header">Skills</h1>
      <div className="page_container">
        <div className="categories_container">
          {categories.map((category) => (
            <Card key={category} className="category">
              <CardHeader className="category_title">
                <CardTitle>{category}</CardTitle>
              </CardHeader>
              <CardContent className="skills_container">
                {grouped[category].map((skill) => (
                  <div key={skill._id} className="skill">
                    <Link href={`/skills/${skill.slug.current}`} className="skill_row_link" aria-label={`View ${skill.title}`}>
                      <div className="skill_label">
                        <div className="skill_img_container">
                          {skill.skillIcon ? <img src={sanityImageUrl(skill.skillIcon, 50)} alt={`${skill.title} Icon`} /> : null}
                        </div>
                        <div className="skill_title_container">
                          <h3 className="skill_title">{skill.title}</h3>
                        </div>
                        <span className="skill_link">
                          <ArrowRightCircle />
                        </span>
                      </div>
                      <Progress value={Number(skill.experience ?? 0) * 10} />
                    </Link>
                  </div>
                ))}
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </>
  );
}

// src/app/skills/skills.component.ts
import { Component, OnInit } from '@angular/core';
import { SanityService } from '../sanity.service';
import { CommonModule } from '@angular/common';
import { SanityImagePipe } from '../sanity-image.pipe';
import { Router, RouterModule } from '@angular/router';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatButtonModule } from '@angular/material/button';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import { ionArrowForwardCircle } from '@ng-icons/ionicons';
import { MatCardModule } from '@angular/material/card';

@Component({
  selector: 'portfolio-skills',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    MatProgressBarModule,
    SanityImagePipe,
    MatButtonModule,
    NgIconComponent,
    MatCardModule,
  ],
  templateUrl: './skills.component.html',
  styleUrl: './skills.component.sass',
  providers: [provideIcons({ ionArrowForwardCircle })],
})
export class SkillsComponent implements OnInit {
  data: any;
  categories: any = [];

  constructor(private sanityService: SanityService, private router: Router) {}

  ngOnInit(): void {
    this.getSkills();
  }

  async getSkills() {
    const data = await this.sanityService.getSkills();
    this.data = this.groupBy(data, 'category');
    this.categories = Object.keys(this.data);
    console.log(this.data);
    return this.data;
  }

  groupBy(objectArray: any, property: any) {
    objectArray.sort(this.compareExperience);
    return objectArray.reduce((acc: any, obj: any) => {
      const key = obj[property];
      const curGroup = acc[key] ?? [];
      return { ...acc, [key]: [...curGroup, obj] };
    }, {});
  }

  compareExperience(a: any, b: any) {
    if (parseInt(a.experience) > parseInt(b.experience)) {
      return -1;
    } else if (parseInt(a.experience) < parseInt(b.experience)) {
      return 1;
    }
    return 0;
  }
}

<h1 class="page_header">Skills</h1>
<div class="page_container">
  <div class="categories_container">
    <mat-card *ngFor="let category of categories" class="category">
      <mat-card-header class="category_title">
        <mat-card-title>
          <h2>{{ category }}</h2>
        </mat-card-title>
      </mat-card-header>
      <div class="skills_container">
        <div *ngFor="let skill of data[category]" class="skill">
          <div class="skill_label">
            <div class="skill_img_container">
              <img
                [src]="skill.skillIcon | sanityImage : 50"
                alt="{{ skill.title }} Icon"
              />
            </div>
            <div class="skill_title_container">
              <h3 class="skill_title">{{ skill.title }}</h3>
            </div>
            <button
              mat-icon-button
              [routerLink]="['/skills', skill.slug.current]"
            >
              <ng-icon name="ionArrowForwardCircle"></ng-icon>
            </button>
          </div>
          <mat-progress-bar
            mode="determinate"
            [value]="skill.experience * 10"
          ></mat-progress-bar>
        </div>
      </div>
    </mat-card>
  </div>
</div>
